spring.application.name=api-concessionaria
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuração do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/concessionaria_desen
spring.datasource.username=postgres
spring.datasource.password=concessionaria321
spring.jpa.properties.hibernate.default_schema=concessionaria